apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: s2i-minimal-notebook-conda
  name: s2i-minimal-notebook-conda
spec:
  lookupPolicy:
    local: true
status:

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: s2i-minimal-notebook-conda
  name: s2i-minimal-notebook-conda
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-minimal-notebook-conda:latest'
  postCommit: {}
  resources:
    requests:
      memory: 6Gi
  runPolicy: Parallel
  source:
    contextDir: minimal-notebook-conda
    git:
      ref: ppc64le
      uri: 'https://github.com/vpavlin/jupyter-notebooks'
    type: Git
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: 's2i-thoth-ubi8-py36:latest'
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
status:
  
