name: tensorflow
channels:
- https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
dependencies:
- python
- tensorflow
- pip
- pip:
  # works for regular pip packages
  - Cython
  - numpy
  - scipy
  - -r requirements.txt
  # and for wheels